# Generated by Django 5.1 on 2024-09-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museic', '0008_likedsong'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedsong',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likedsong',
            name='user',
        ),
    ]
